version: "3"
services:
  backend:
    build:
      context: ./todo-api
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - API_PORT=some_value_here
      - MONGO_URL=some_value_here
      - JWT_ACCESS_TOKEN_SECRET=some_value_here
      - JWT_ACCESS_TOKEN_EXPIRES_IN=some_value_here
      - JWT_REFRESH_TOKEN_SECRET=some_value_here
      - JWT_REFRESH_TOKEN_EXPIRES_IN=some_value_here
    networks:
      - mynetwork

  frontend:
    build:
      context: ./front

    ports:
      - 3000:80
    networks:
      - mynetwork

networks:
  mynetwork:
